### ISSUE TITLE
Why the calculated sunrise time is different to the actual one?

### ISSUE THREAD

**Issue by xuesongle** [ssefick/StreamMetabolism#1]
@ssefick Hi,  I am confusing about how to use sunrise
For example, given the following information:

Sacramento, Capital of California 38.575764, -121.478851, 
Standard time zone:	UTC/GMT -7 hours UTC/GMT -7:00 hours (Pacific Daylight Time)
6:07 am sunrise local time on 2019/05/04

Testing with the provided function sunrise.set

```
lat_ <- 38.575764
lon_ <- -121.478851

library("StreamMetabolism")
sunrise.set(lat_, -lon_, "2019/05/04", timezone="UTC+7") 
```

Result shows that

```
                   sunrise              sunset
newlon 2019-05-03 13:54:18 2019-05-04 03:48:09
```
I could not figure out why the calculated time is so different? Is the calculated in UTC+7 time or local time?

**Comment by ssefick** [comment]
Did you mean to calculate the sunrise/sunset in the yellow sea in Eastern Time (UTC+7)? You made the decimal degree coordinate for longitude positive. Please help me understand if I have misunderstood something.
