### ISSUE TITLE
Remove use of maptools

### ISSUE THREAD

**Issue by rsbivand** [ssefick/StreamMetabolism#2]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by rsbivand** [comment]
@ssefick See also https://r-spatial.org/r/2023/04/10/evolution3.html and https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN. The `suntools` package is on CRAN https://cran.r-project.org/package=suntools.

**Comment by rsbivand** [comment]
@ssefick Less than three weeks remain to fix this.

**Comment by ssefick** [comment]
Thanks Dr. Bivand. I just finished building my house, moved in, and found my laptop chord the other day. I will get working on this in the mornings. Shall I use this channel to ask questions?

**Comment by ssefick** [comment]
I believe that sunrise is the only map tools function the package uses in the.

The suntools package seems to have this function.

I will migrate in the next week.

**Comment by rsbivand** [comment]
@ssefick R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos.

**Comment by ssefick** [comment]
On CRAN sorry for requiring so many reminders.

**Comment by rsbivand** [comment]
@ssefick Thanks for your patience! I sometimes think that we've got used to systems sending push notifications, memory seems to need more support.
